var hierarchy =
[
    [ "_RIP_MSG_FIXED", "struct___r_i_p___m_s_g___f_i_x_e_d.html", null ],
    [ "AccelStepper", "class_accel_stepper.html", null ],
    [ "RtcAlarmManager< V_CALLBACK >::Alarm", "struct_rtc_alarm_manager_1_1_alarm.html", null ],
    [ "arp_entry", "structarp__entry.html", null ],
    [ "arp_hdr", "structarp__hdr.html", null ],
    [ "astro_angle_result_t", "structastro__angle__result__t.html", null ],
    [ "astro_apsis_t", "structastro__apsis__t.html", null ],
    [ "astro_constellation_t", "structastro__constellation__t.html", null ],
    [ "astro_eclipse_event_t", "structastro__eclipse__event__t.html", null ],
    [ "astro_ecliptic_t", "structastro__ecliptic__t.html", null ],
    [ "astro_elongation_t", "structastro__elongation__t.html", null ],
    [ "astro_equatorial_t", "structastro__equatorial__t.html", null ],
    [ "astro_func_result_t", "structastro__func__result__t.html", null ],
    [ "astro_global_solar_eclipse_t", "structastro__global__solar__eclipse__t.html", null ],
    [ "astro_horizon_t", "structastro__horizon__t.html", null ],
    [ "astro_hour_angle_t", "structastro__hour__angle__t.html", null ],
    [ "astro_illum_t", "structastro__illum__t.html", null ],
    [ "astro_local_solar_eclipse_t", "structastro__local__solar__eclipse__t.html", null ],
    [ "astro_lunar_eclipse_t", "structastro__lunar__eclipse__t.html", null ],
    [ "astro_moon_quarter_t", "structastro__moon__quarter__t.html", null ],
    [ "astro_observer_t", "structastro__observer__t.html", null ],
    [ "astro_rotation_t", "structastro__rotation__t.html", null ],
    [ "astro_search_result_t", "structastro__search__result__t.html", null ],
    [ "astro_seasons_t", "structastro__seasons__t.html", null ],
    [ "astro_spherical_t", "structastro__spherical__t.html", null ],
    [ "astro_time_t", "structastro__time__t.html", null ],
    [ "astro_transit_t", "structastro__transit__t.html", null ],
    [ "astro_utc_t", "structastro__utc__t.html", null ],
    [ "astro_vector_t", "structastro__vector__t.html", null ],
    [ "BfButton", "class_bf_button.html", null ],
    [ "Client", null, [
      [ "EthernetClient", "class_ethernet_client.html", null ]
    ] ],
    [ "DhcpClass", "class_dhcp_class.html", null ],
    [ "DNSClient", "class_d_n_s_client.html", null ],
    [ "DS3231AlarmOne", "class_d_s3231_alarm_one.html", null ],
    [ "DS3231AlarmTwo", "class_d_s3231_alarm_two.html", null ],
    [ "DS3234AlarmOne", "class_d_s3234_alarm_one.html", null ],
    [ "DS3234AlarmTwo", "class_d_s3234_alarm_two.html", null ],
    [ "EepromAt24c32< T_WIRE_METHOD >", "class_eeprom_at24c32.html", null ],
    [ "EthernetServer", "class_ethernet_server.html", [
      [ "EthernetServerPrint", "class_ethernet_server_print.html", null ]
    ] ],
    [ "ethip_hdr", "structethip__hdr.html", null ],
    [ "fontinfo", "structfontinfo.html", null ],
    [ "fontMetrics", "structfont_metrics.html", null ],
    [ "TFT_eSPI::fontMetrics", "struct_t_f_t__e_s_p_i_1_1font_metrics.html", null ],
    [ "memblock", "structmemblock.html", null ],
    [ "MemoryPool", "class_memory_pool.html", [
      [ "Enc28J60Network", "class_enc28_j60_network.html", null ]
    ] ],
    [ "MultiStepper", "class_multi_stepper.html", null ],
    [ "PCF8563Alarm", "class_p_c_f8563_alarm.html", null ],
    [ "Print", null, [
      [ "EthernetServerPrint", "class_ethernet_server_print.html", null ],
      [ "TFT_eSPI", "class_t_f_t__e_s_p_i.html", [
        [ "TFT_eSprite", "class_t_f_t__e_sprite.html", null ]
      ] ]
    ] ],
    [ "RtcAlarmManager< V_CALLBACK >", "class_rtc_alarm_manager.html", null ],
    [ "RtcDateTime", "class_rtc_date_time.html", null ],
    [ "RtcDS1302< T_WIRE_METHOD >", "class_rtc_d_s1302.html", null ],
    [ "RtcDS1307< T_WIRE_METHOD >", "class_rtc_d_s1307.html", null ],
    [ "RtcDS3231< T_WIRE_METHOD >", "class_rtc_d_s3231.html", [
      [ "RtcDS3232< T_WIRE_METHOD >", "class_rtc_d_s3232.html", null ]
    ] ],
    [ "RtcDS3234< T_SPI_METHOD >", "class_rtc_d_s3234.html", null ],
    [ "RtcHourAmPm", "class_rtc_hour_am_pm.html", null ],
    [ "RtcLocaleEn", "class_rtc_locale_en.html", null ],
    [ "RtcLocaleEnUs", "class_rtc_locale_en_us.html", null ],
    [ "RtcPCF8563< T_WIRE_METHOD >", "class_rtc_p_c_f8563.html", null ],
    [ "RtcTemperature", "class_rtc_temperature.html", null ],
    [ "RtcTimeZone", "struct_rtc_time_zone.html", null ],
    [ "setup_t", "structsetup__t.html", null ],
    [ "TFT_eSPI_Button", "class_t_f_t__e_s_p_i___button.html", null ],
    [ "ThreeWire", "class_three_wire.html", null ],
    [ "UDP", null, [
      [ "EthernetUDP", "class_ethernet_u_d_p.html", null ]
    ] ],
    [ "uip_conn", "structuip__conn.html", null ],
    [ "uip_eth_addr", "structuip__eth__addr.html", null ],
    [ "uip_eth_hdr", "structuip__eth__hdr.html", null ],
    [ "uip_icmpip_hdr", "structuip__icmpip__hdr.html", null ],
    [ "uip_stats", "structuip__stats.html", null ],
    [ "uip_tcpip_hdr", "structuip__tcpip__hdr.html", null ],
    [ "uip_udp_conn", "structuip__udp__conn.html", null ],
    [ "uip_udp_msg_rec_t", "structuip__udp__msg__rec__t.html", null ],
    [ "uip_udp_userdata_t", "structuip__udp__userdata__t.html", null ],
    [ "uip_udpip_hdr", "structuip__udpip__hdr.html", null ],
    [ "uip_userdata_closed_t", "structuip__userdata__closed__t.html", null ],
    [ "uip_userdata_t", "structuip__userdata__t.html", null ],
    [ "UIPEthernetClass", "class_u_i_p_ethernet_class.html", null ]
];